import type { NextConfig } from 'next';

/**
 * Next.js configuration for static export mode.
 *
 * Outputs a fully static site to the `out/` directory. Image optimization
 * is disabled since artwork thumbnails are pre-generated by the Python pipeline.
 *
 * For GitHub Pages deployment at https://liamlaverty.github.io/paint-by-language-model/
 */
const nextConfig: NextConfig = {
  output: 'export',
  basePath: process.env.NODE_ENV === 'production' ? '/paint-by-language-model' : '',
  assetPrefix: process.env.NODE_ENV === 'production' ? '/paint-by-language-model/' : '',
  images: {
    unoptimized: true,
  },
};

export default nextConfig;
