import type { NextConfig } from 'next';

/**
 * Next.js configuration for static export mode.
 *
 * Outputs a fully static site to the `out/` directory. Image optimization
 * is disabled since artwork thumbnails are pre-generated by the Python pipeline.
 */
const nextConfig: NextConfig = {
  output: 'export',
  images: {
    unoptimized: true,
  },
};

export default nextConfig;
