/**
 * TypeScript type definitions for viewer data model.
 *
 * Defines interfaces matching the viewer_data.json schema produced by
 * the Python generation orchestrator.
 */

/**
 * Batch-level generation statistics.
 *
 * @property {number} strokes_per_query_configured - Strokes requested per VLM query
 * @property {number} total_strokes_requested - Total strokes requested across all iterations
 * @property {number} total_strokes_applied - Total strokes successfully applied
 * @property {number} total_strokes_skipped - Total strokes that failed validation
 * @property {Record<string, number>} stroke_type_breakdown - Count of strokes by type
 */
export interface BatchStatistics {
  strokes_per_query_configured: number;
  total_strokes_requested: number;
  total_strokes_applied: number;
  total_strokes_skipped: number;
  stroke_type_breakdown: Record<string, number>;
}

/**
 * A single layer in the painting plan.
 *
 * @property {number} layer_number - Sequential layer number (1-based)
 * @property {string} name - Layer name
 * @property {string} description - Layer description
 * @property {string[]} colour_palette - Hex colour codes for this layer
 * @property {string[]} stroke_types - Allowed stroke types for this layer
 * @property {string} techniques - Technique description
 * @property {string[]} [shapes] - Optional shape hints
 * @property {string[]} [highlights] - Optional highlight notes
 */
export interface PaintingPlanLayer {
  layer_number: number;
  name: string;
  description: string;
  colour_palette: string[];
  stroke_types: string[];
  techniques: string;
  shapes?: string[];
  highlights?: string[];
}

/**
 * VLM-generated painting plan with layer breakdown.
 *
 * @property {string} artist_name - Target artist style
 * @property {string} subject - Subject description
 * @property {string} [expanded_subject] - Detailed subject description
 * @property {number} total_layers - Number of planned layers
 * @property {PaintingPlanLayer[]} layers - Ordered array of layer definitions
 * @property {string} overall_notes - High-level painting strategy notes
 */
export interface PaintingPlan {
  artist_name: string;
  subject: string;
  expanded_subject?: string;
  total_layers: number;
  layers: PaintingPlanLayer[];
  overall_notes: string;
}

/**
 * Per-iteration evaluation feedback from the VLM evaluator.
 *
 * @property {number} iteration - Iteration index (1-based)
 * @property {number} score - Style similarity score (0-100)
 * @property {string} feedback - Qualitative assessment from the evaluator
 * @property {string} strengths - What aspects work well stylistically
 * @property {string} suggestions - Areas for improvement
 */
export interface EvaluationDetail {
  iteration: number;
  score: number;
  feedback: string;
  strengths: string;
  suggestions: string;
}

/**
 * Complete viewer data loaded from viewer_data.json.
 *
 * @property {ArtworkMetadata} metadata - Artwork-level metadata (dimensions, artist, scores, etc.)
 * @property {PaintingPlan | null} [painting_plan] - VLM-generated painting plan, if available
 * @property {EnrichedStroke[]} strokes - Ordered array of enriched strokes with rendering and context data
 * @property {EvaluationDetail[]} [evaluations] - Per-iteration evaluation feedback from the VLM evaluator
 */
export interface ViewerData {
  metadata: ArtworkMetadata;
  painting_plan?: PaintingPlan | null;
  strokes: EnrichedStroke[];
  evaluations?: EvaluationDetail[];
}

/**
 * Artwork-level metadata embedded in viewer_data.json.
 *
 * @property {string} artwork_id - Unique identifier for this generation run
 * @property {string} artist_name - Name of the artist style used for generation
 * @property {string} subject - Subject description provided to the VLM
 * @property {string} [expanded_subject] - Detailed subject description generated by the planner
 * @property {number} canvas_width - Canvas width in pixels
 * @property {number} canvas_height - Canvas height in pixels
 * @property {string} background_color - Background color as hex string (e.g. "#FFFFFF")
 * @property {number} total_strokes - Total number of successfully applied strokes
 * @property {number} total_iterations - Total number of VLM query iterations
 * @property {number[]} score_progression - Evaluation score at each iteration (0-100)
 * @property {string} [generation_date] - ISO 8601 timestamp when generation started
 * @property {{ stroke_generator: string; evaluator: string }} [vlm_models] - VLM model identifiers used during generation
 * @property {number | null} [final_score] - Final evaluation score (0-100), or null if not evaluated
 * @property {string | null} [planner_model] - Model identifier used for the planning phase
 * @property {BatchStatistics | null} [batch_statistics] - Aggregate stroke generation statistics
 * @property {Record<string, number> | null} [layer_progression] - Score keyed by layer name/number
 */
export interface ArtworkMetadata {
  artwork_id: string;
  artist_name: string;
  subject: string;
  expanded_subject?: string | null;
  canvas_width: number;
  canvas_height: number;
  background_color: string;
  total_strokes: number;
  total_iterations: number;
  score_progression: number[];
  generation_date?: string;
  vlm_models?: {
    stroke_generator: string;
    evaluator: string;
  };
  final_score?: number | null;
  planner_model?: string | null;
  batch_statistics?: BatchStatistics | null;
  layer_progression?: Record<string, number> | null;
}

/**
 * A single stroke enriched with iteration context and batch reasoning.
 *
 * Extends the base Stroke rendering parameters with metadata fields
 * (index, iteration, batch_position, batch_reasoning) added during
 * viewer data export.
 *
 * @property {number} index - Global sequential index (0-based) across all iterations
 * @property {number} iteration - Which VLM query iteration produced this stroke
 * @property {number} batch_position - Position within the iteration's batch (0-based)
 * @property {string} batch_reasoning - VLM's reasoning text for the batch that contains this stroke
 * @property {'line' | 'arc' | 'polyline' | 'circle' | 'splatter' | 'dry-brush' | 'chalk' | 'wet-brush' | 'burn' | 'dodge'} type - Stroke rendering type
 * @property {string} color_hex - Stroke color as hex string
 * @property {number} thickness - Stroke line thickness in pixels
 * @property {number} opacity - Stroke opacity (0.0 to 1.0)
 * @property {number} [start_x] - Line start X coordinate
 * @property {number} [start_y] - Line start Y coordinate
 * @property {number} [end_x] - Line end X coordinate
 * @property {number} [end_y] - Line end Y coordinate
 * @property {[number, number, number, number]} [arc_bbox] - Arc bounding box [x0, y0, x1, y1]
 * @property {number} [arc_start_angle] - Arc start angle in degrees
 * @property {number} [arc_end_angle] - Arc end angle in degrees
 * @property {[number, number][]} [points] - Array of [x, y] coordinate pairs for polyline vertices
 * @property {number} [center_x] - Circle center X coordinate
 * @property {number} [center_y] - Circle center Y coordinate
 * @property {number} [radius] - Circle radius in pixels
 * @property {boolean} [fill] - Whether the circle is filled (true) or outlined (false)
 * @property {number} [splatter_count] - Number of random dots in the splatter
 * @property {number} [splatter_radius] - Maximum distance from center for splatter dots
 * @property {number} [dot_size_min] - Minimum dot radius in pixels
 * @property {number} [dot_size_max] - Maximum dot radius in pixels
 * @property {number} [brush_width] - Total width of brush perpendicular to stroke direction (dry-brush)
 * @property {number} [bristle_count] - Number of parallel bristle lines (dry-brush)
 * @property {number} [gap_probability] - Probability of bristle segment being skipped (dry-brush)
 * @property {number} [chalk_width] - Width of chalk mark perpendicular to path (chalk)
 * @property {number} [grain_density] - Number of random dots per sample point along path (chalk)
 * @property {number} [softness] - Gaussian blur radius for edge bleed (wet-brush)
 * @property {number} [flow] - Paint density/concentration multiplied with opacity (wet-brush)
 * @property {number} [intensity] - Amount of darkening (burn) or lightening (dodge)
 */
export interface EnrichedStroke {
  index: number;
  iteration: number;
  batch_position: number;
  batch_reasoning: string;
  type:
    | 'line'
    | 'arc'
    | 'polyline'
    | 'circle'
    | 'splatter'
    | 'dry-brush'
    | 'chalk'
    | 'wet-brush'
    | 'burn'
    | 'dodge';
  color_hex: string;
  thickness: number;
  opacity: number;
  start_x?: number;
  start_y?: number;
  end_x?: number;
  end_y?: number;
  arc_bbox?: [number, number, number, number];
  arc_start_angle?: number;
  arc_end_angle?: number;
  points?: [number, number][];
  center_x?: number;
  center_y?: number;
  radius?: number;
  fill?: boolean;
  splatter_count?: number;
  splatter_radius?: number;
  dot_size_min?: number;
  dot_size_max?: number;
  brush_width?: number;
  bristle_count?: number;
  gap_probability?: number;
  chalk_width?: number;
  grain_density?: number;
  softness?: number;
  flow?: number;
  intensity?: number;
}

/**
 * Summary of an artwork for the homepage gallery.
 *
 * Contains a subset of metadata suitable for rendering a preview
 * card without loading the full stroke data.
 *
 * @property {string} artworkId - Artwork identifier (matches directory name in public/data/)
 * @property {string} artistName - Display name of the artist style
 * @property {string} subject - Subject description
 * @property {number} totalStrokes - Number of strokes in the finished artwork
 * @property {number} totalIterations - Number of VLM iterations used
 * @property {string | null} thumbnailUrl - URL to the thumbnail image, or null if not available
 * @property {string | null} generationDate - ISO 8601 timestamp when generation started, or null if missing
 * @property {string | null} modelName - Stroke generator VLM model name, or null if missing
 * @property {number | null} finalScore - Final evaluation score (0-100)
 */
export interface ArtworkSummary {
  artworkId: string;
  artistName: string;
  subject: string;
  totalStrokes: number;
  totalIterations: number;
  thumbnailUrl: string | null;
  generationDate: string | null;
  modelName: string | null;
  finalScore: number | null;
}
